name: worm-graph
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pytorch-gpu
  - scikit-learn
  - pytorch=1.13
  - black
  - networkx
  - black-jupyter
  - ipywidgets
  - hydra-core
  - pip
  - pandas
  - nomkl
  - freetype
  - python=3.9
  - numpy
  - seaborn
  - scipy
  - scikit-learn
  - scikit-learn-intelex
  - omegaconf
  - h5py
  - notebook
  - mat73
  - tqdm
  - jupyterlab
  - pip:
      - torch-geometric
      - hydra-submitit-launcher
      - hydra-joblib-launcher
      - ncps
# prefix: /om2/user/qsimeon/miniconda/envs/worm-graph
