name: worm-graph
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
  - defaults
dependencies:
  - python=3.9
  # large, complex dependencies
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - notebook
  - seaborn
  # dependencies with moderate complexity
  - h5py
  - networkx
  - ipython
  - typing
  - typing_extensions
  # small, simple dependencies
  - tqdm
  - pip
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8 # uncomment if you have a GPU
  - omegaconf
  - black
  - "black[jupyter]"
  - pip:
    - torch-geometric
    - hydra-core
    - hydra-submitit-launcher
    - hydra-optuna-sweeper
    - pysindy
    - pytest
    - requests
    - mat73
    - ncps
